# Generated by Django 5.2.3 on 2025-07-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField()),
                ('Solution', models.TimeField()),
                ('audience', models.TextField()),
                ('unique_value', models.TextField()),
                ('revenue_model', models.TextField()),
                ('known_competitors', models.TextField()),
            ],
        ),
    ]
