# Generated by Django 5.2.3 on 2025-07-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideas',
            old_name='audience',
            new_name='market',
        ),
        migrations.RenameField(
            model_name='ideas',
            old_name='Solution',
            new_name='solution',
        ),
    ]
