# Generated by Django 5.2.3 on 2025-07-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_audience_ideas_market_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='solution',
            field=models.TextField(),
        ),
    ]
