# Generated by Django 5.2.3 on 2025-07-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='opportunities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideas',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideas',
            name='threats',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideas',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
