# Generated by Django 5.2.3 on 2025-07-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_ideas_opportunities_ideas_strengths_ideas_threats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='score_opportunities',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ideas',
            name='score_strengths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ideas',
            name='score_threats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ideas',
            name='score_weaknesses',
            field=models.IntegerField(default=0),
        ),
    ]
