# Generated by Django 5.2.3 on 2025-07-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_ideas_score_opportunities_ideas_score_strengths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
