# Generated by Django 5.2.3 on 2025-07-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_ideas_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='market_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
