# Generated by Django 5.2 on 2026-04-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_ideas_market_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ideas',
            name='idea_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
