# Generated by Django 5.2 on 2026-04-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_ideas_blockchain_tx_hash_ideas_idea_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideas',
            name='blockchain_tx_hash',
        ),
        migrations.RemoveField(
            model_name='ideas',
            name='idea_hash',
        ),
        migrations.AddField(
            model_name='ideas',
            name='prd_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
