# Generated by Django 5.2 on 2026-04-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_ideas_blockchain_tx_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ideas',
            name='idea_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
